version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./adminer.conf:/etc/nginx/conf.d/default.conf
    networks:
      - front
      - backend
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
    restart: always

  adminer:
    image: adminer
    networks:
      - backend
      - databases
    restart: always

networks:
  front:
    external:
      name: front
  databases:
    external:
      name: databases
  backend:
