version: '3'
services:
  adminer:
    image: adminer
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - front
      - databases
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
    restart: always

networks:
  front:
    external:
      name: front
  databases:
    external:
      name: databases
